# the next level is in the zip file generated by this script
# the password is invader in reserve sequence. That's 'redavni'.

import requests
import re

URL="http://butter:fly@www.pythonchallenge.com/pc/hex/unreal.jpg"
proxy = {
    'http': 'child-prc.intel.com:913',
    'https': 'child-prc.intel.com:913',
}

# start-end/total
pattern = "(\d+)[-](\d+)/(\d+)"

size = None
header = None
length = 0 

def get_size(size):
    header = None
    if size:
        header = {
                    'Range': 'bytes=%i-' % int(size),
                    'cache-control': "no-cache",
                 }
        print header
    
    r = requests.get(URL, proxies=proxy, headers=header)
    rng = r.headers['Content-Range']
    
    print rng
    match = re.findall(pattern, rng)
    if match:
        start, end, length = match[0]
    if len(r.text) < 100:
        print r.text
    return start, end, length

while True:

    try:
        start, size, length = get_size(size)
        size = int(size) + 1
    except:
        break

print length

start = length
while True:
    try:
        start, end, l = get_size(start)
        start = int(start) - 1
#    print r.headers
#    print r.text
    except Exception as e:
        break


rang = 1152983631
header = {
            'Range': 'bytes=%i-' % int(rang),
            'cache-control': "no-cache",
        }

print header
r = requests.get(URL, proxies=proxy, headers=header)
r.raise_for_status()

with open("21.zip", 'w+b') as f:
    f.write(r.content)
 
